name: Hexo Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      echo: "init node successful"

    - name: Install hexo
      run: npm install -g hexo-cli --save
      echo: "init hexo successful"

    - name: Build Hexo
      run: hexo clean
      run: hexo g
      echo: "build successful"

    - name: Deploy to GitHub Pages
      uses: hexo deploy
      echo: "deploy successful"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public 
        publish_branch: build