name: Hexo Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install hexo
      run: npm install -g hexo-cli --save

    - name: Build Hexo
      run: hexo clean
      run: hexo g

    - name: Deploy to GitHub Pages
      uses: hexo d